import{q as H,v as K,ct as W,R as q}from"./DAuuuMsE.js";var v={exports:{}},T={},R={exports:{}},A={},g;function B(){if(g)return A;g=1;/**
 * @license React
 * use-sync-external-store-shim.development.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */return function(){function e(r,n){return r===n&&(r!==0||1/r===1/n)||r!==r&&n!==n}function t(r,n){f||o.startTransition===void 0||(f=!0,console.error("You are using an outdated, pre-release alpha of React 18 that does not support useSyncExternalStore. The use-sync-external-store shim will not work correctly. Upgrade to a newer pre-release."));var s=n();if(!d){var l=n();a(s,l)||(console.error("The result of getSnapshot should be cached to avoid an infinite loop"),d=!0)}l=L({inst:{value:s,getSnapshot:n}});var c=l[0].inst,S=l[1];return b(function(){c.value=s,c.getSnapshot=n,u(c)&&S({inst:c})},[r,s,n]),h(function(){return u(c)&&S({inst:c}),r(function(){u(c)&&S({inst:c})})},[r]),_(s),s}function u(r){var n=r.getSnapshot;r=r.value;try{var s=n();return!a(r,s)}catch{return!0}}function i(r,n){return n()}typeof __REACT_DEVTOOLS_GLOBAL_HOOK__<"u"&&typeof __REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStart=="function"&&__REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStart(Error());var o=H(),a=typeof Object.is=="function"?Object.is:e,L=o.useState,h=o.useEffect,b=o.useLayoutEffect,_=o.useDebugValue,f=!1,d=!1,p=typeof window>"u"||typeof window.document>"u"||typeof window.document.createElement>"u"?i:t;A.useSyncExternalStore=o.useSyncExternalStore!==void 0?o.useSyncExternalStore:p,typeof __REACT_DEVTOOLS_GLOBAL_HOOK__<"u"&&typeof __REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStop=="function"&&__REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStop(Error())}(),A}var V;function z(){return V||(V=1,R.exports=B()),R.exports}var w;function F(){if(w)return T;w=1;/**
 * @license React
 * use-sync-external-store-shim/with-selector.development.js
 *
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */return function(){function e(_,f){return _===f&&(_!==0||1/_===1/f)||_!==_&&f!==f}typeof __REACT_DEVTOOLS_GLOBAL_HOOK__<"u"&&typeof __REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStart=="function"&&__REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStart(Error());var t=H(),u=z(),i=typeof Object.is=="function"?Object.is:e,o=u.useSyncExternalStore,a=t.useRef,L=t.useEffect,h=t.useMemo,b=t.useDebugValue;T.useSyncExternalStoreWithSelector=function(_,f,d,p,r){var n=a(null);if(n.current===null){var s={hasValue:!1,value:null};n.current=s}else s=n.current;n=h(function(){function c(O){if(!S){if(S=!0,m=O,O=p(O),r!==void 0&&s.hasValue){var E=s.value;if(r(E,O))return y=E}return y=O}if(E=y,i(m,O))return E;var D=p(O);return r!==void 0&&r(E,D)?(m=O,E):(m=O,y=D)}var S=!1,m,y,x=d===void 0?null:d;return[function(){return c(f())},x===null?void 0:function(){return c(x())}]},[f,d,p,r]);var l=o(_,n[0],n[1]);return L(function(){s.hasValue=!0,s.value=l},[l]),b(l),l},typeof __REACT_DEVTOOLS_GLOBAL_HOOK__<"u"&&typeof __REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStop=="function"&&__REACT_DEVTOOLS_GLOBAL_HOOK__.registerInternalModuleStop(Error())}(),T}var I;function U(){return I||(I=1,v.exports=F()),v.exports}var k=U();const $=K(k),{useSyncExternalStoreWithSelector:Y}=$,J=e=>e;function N(e,t=J,u){const i=Y(e.subscribe,e.getState,e.getInitialState,t,u);return q.useDebugValue(i),i}const j=(e,t)=>{const u=W(e),i=(o,a=t)=>N(u,o,a);return Object.assign(i,u),i},X=(e,t)=>e?j(e,t):j,G=e=>Symbol.iterator in e,M=e=>"entries"in e,C=(e,t)=>{const u=e instanceof Map?e:new Map(e.entries()),i=t instanceof Map?t:new Map(t.entries());if(u.size!==i.size)return!1;for(const[o,a]of u)if(!Object.is(a,i.get(o)))return!1;return!0},P=(e,t)=>{const u=e[Symbol.iterator](),i=t[Symbol.iterator]();let o=u.next(),a=i.next();for(;!o.done&&!a.done;){if(!Object.is(o.value,a.value))return!1;o=u.next(),a=i.next()}return!!o.done&&!!a.done};function Z(e,t){return Object.is(e,t)?!0:typeof e!="object"||e===null||typeof t!="object"||t===null?!1:!G(e)||!G(t)?C({entries:()=>Object.entries(e)},{entries:()=>Object.entries(t)}):M(e)&&M(t)?C(e,t):P(e,t)}export{X as c,Z as s};
